Blogger\BlogBundle\Entity\Enquiry:
    properties:
        name:
            - NotBlank: ~
        subject:
            - NotBlank: ~
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
        body:
            - Length:
                min: 2
                max: 50
